# https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema?view=vsts

trigger:
  batch: true
  branches:
    include:
      - "master"

pr:
  autoCancel: true
  branches:
    include:
      - master

# build name ($(Build.BuildNumber))
name: $(Year:yy)$(DayOfYear)$(Rev:rr)

pool:
  vmImage: "windows-latest"

variables:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  BuildConfiguration: "Release"
  Project: "$(Build.SourcesDirectory)/*.sln"

steps:
  - task: UseDotNet@2
    displayName: "Install dotnet core SDK"
    inputs:
      packageType: "sdk"
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: "Restore"
    inputs:
      command: "restore"
      projects: "$(Project)"

  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: "build"
      projects: "$(Project)"
      arguments: "--configuration $(buildConfiguration) --no-restore"

  - task: DotNetCoreCLI@2
    displayName: "Test"
    inputs:
      command: "test"
      projects: "$(Project)"
      arguments: "--configuration $(buildConfiguration)"
      publishTestResults: true
      testRunTitle: "$(Build.BuildNumber)"

  - task: DotNetCoreCLI@2
    displayName: "Pack $(buildConfiguration)"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: "pack"
      packagesToPack: "$(Project)"
      nobuild: true
      versioningScheme: "byPrereleaseNumber"
      majorVersion: "1"
      minorVersion: "0"
      patchVersion: "0"
      verbosityPack: "Normal"

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "Medesa.Databases"
      publishLocation: "Container"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
