//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from f:\Private\NetCore.AntlrCodeCompletion\test\NetCore.UnitTestAntlrCodeCompletion\Grammar\Expr.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ExprParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IExprListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ExprParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ExprParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] ExprParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] ExprParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleExpression([NotNull] ExprParser.SimpleExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleExpression([NotNull] ExprParser.SimpleExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.variableRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableRef([NotNull] ExprParser.VariableRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.variableRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableRef([NotNull] ExprParser.VariableRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExprParser.functionRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionRef([NotNull] ExprParser.FunctionRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExprParser.functionRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionRef([NotNull] ExprParser.FunctionRefContext context);
}
} // namespace Grammar
